apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
images:
- name: ghcr.io/argocon2022-workshop/demo-app
  newName: ghcr.io/noiseoverip/demo-app
  newTag: 9fdc2fa02d9b1a658ae6018b8f68dc9bcabc0590
